--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElementalMinecraftGaming/StableMythicWarriors
build-by-default: true
branches:
- master
projects:
  StableMythicWarriors:
    path: ""
...
